#2nd try
name: Build, scan and push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  REGISTRY: quay.io
  IMAGE_NAME: mvilar6/shift_left #error en el nom (diferencia entre noms de repo)

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set image variables
        run: |
          echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "FULL_IMAGE=${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t "$FULL_IMAGE" .

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FULL_IMAGE }}
          severity: 'HIGH,CRITICAL'
          format: 'table'
          exit-code: '1'


      - name: Generate SBOM (Syft)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$PWD":/work \
            anchore/syft:latest "$FULL_IMAGE" -o syft-json > sbom.syft.json
          test -s sbom.syft.json && echo "SBOM created: sbom.syft.json"

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-syft-json
          path: sbom.syft.json
          if-no-files-found: error
          retention-days: 14



      - name: Vulnerability scan (Grype on SBOM)
        run: |
          docker run --rm \
            -v "$PWD":/work \
            anchore/grype:latest /work/sbom.syft.json \
            --fail-on high \
            --only-fixed=false \
            --add-cpes-if-none

      - name: Commit SBOM to Repo
        if: success()
        run: |
          mkdir -p sbom
          cp sbom.syft.json sbom/sbom-${TAG}.json

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add sbom/sbom-${TAG}.json
          git commit -m "Add SBOM for image tag ${TAG}" || echo "No changes to commit"
          git push origin HEAD:main


      - name: Push image
        if: success()
        run: |
          docker push "$FULL_IMAGE"
